name: ❓Question
description: Ask a question about this mod
labels: ["question", "medium priority"]
assignees: ["Crystal-Spider"]
body:
- type: checkboxes
  attributes:
    label: I have confirmed no other issues report this bug
    description: Please search if an issue already exists for the bug you've encountered.
    options:
    - label: I have searched for existing issues
      required: true
- type: textarea
  attributes:
    label: Question
    description: Ask a question about this mod.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Insert here anything that will give us more context about the issue you are encountering.
